Rails:
  Enabled: true

Metrics/LineLength:
  Max: 120

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

# specs tend to get long
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
